---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: open-webui
  labels:
    app: open-webui
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
